#!/bin/env bash

# stop previously running instance if any
source ./stop
# install require deps
source ./install



export PORT=80 
echo "server is running on Port: ${PORT}"
# start server
source ./run &> ./server.log &

